version: '3'

networks:
  thoughts-beta-network:
    driver: bridge

volumes:
  prometheus_data: {}
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
    - ./data/db_data:/var/lib/mysql
    - ./config/mysql/init:/docker-entrypoint-initdb.d/
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--default-time-zone=+8:00'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flash_sale
      MYSQL_USER: thoughts-beta
      MYSQL_PASSWORD: thoughts-beta
    ports:
    - 3306:3306
    networks:
    - thoughts-beta-network

  redis:
    container_name: redis
    image: redislabs/redismod:latest
    ports:
    - 6379:6379
    networks:
    - thoughts-beta-network

  rmqnamesrv:
    image: apacherocketmq/rocketmq:4.5.0
    container_name: rmqnamesrv
    ports:
    - 9876:9876
    volumes:
    - ./data/rocketmq/logs:/home/rocketmq/logs
    - ./data/rocketmq/store:/home/rocketmq/store
    command: sh mqnamesrv
    networks:
    - thoughts-beta-network
  rmqbroker:
    image: apacherocketmq/rocketmq:4.5.0
    container_name: rmqbroker
    ports:
    - 10909:10909
    - 10911:10911
    - 10912:10912
    volumes:
    - ./data/rocketmq/logs:/home/rocketmq/logs
    - ./data/rocketmq/store:/home/rocketmq/store
    - ./config/rocketmq/broker.conf:/home/rocketmq/rocketmq-4.5.0/conf/broker.conf
    command: sh mqbroker -n rmqnamesrv:9876 -c ../conf/broker.conf
    depends_on:
    - rmqnamesrv
    environment:
    - JAVA_HOME=/usr/lib/jvm/jre
    networks:
    - thoughts-beta-network

  elasticsearch:
    image: elasticsearch:7.14.2
    container_name: elasticsearch
    volumes:
    - type: bind
      source: ./config/elk/elasticsearch.yml
      target: /usr/share/elasticsearch/config/elasticsearch.yml
      read_only: true
    ports:
    - "9200:9200"
    - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    networks:
    - thoughts-beta-network

  logstash:
    image: logstash:7.14.2
    container_name: logstash
    volumes:
    - type: bind
      source: ./config/elk/logstash.yml
      target: /usr/share/logstash/config/logstash.yml
      read_only: true
    - type: bind
      source: ./config/elk/pipeline
      target: /usr/share/logstash/pipeline
      read_only: true
    ports:
    - "5044:5044"
    - "5000:5000/tcp"
    - "5000:5000/udp"
    - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
    - thoughts-beta-network
    depends_on:
    - elasticsearch

  kibana:
    image: kibana:7.14.2
    container_name: kibana
    volumes:
    - type: bind
      source: ./config/elk/kibana.yml
      target: /usr/share/kibana/config/kibana.yml
      read_only: true
    ports:
    - "5601:5601"
    networks:
    - thoughts-beta-network
    depends_on:
    - elasticsearch


